### ISSUE TITLE
Syncing of calibiration frame stacking routines

### ISSUE THREAD

**Issue by outyprouty** [umbc-research/data-redux#5]
Two different top-of-telescope calibration routines return different instrument magnitude results. We expect that this is due to different stacking/accumulation functions being used to create master Darks and Flats. Please investigate the differences in the two code bases. Averaging is not the same as medianing which is not the same as moding. We should pick one and run with it. Report which code base is using what and which accumulation function we run with.

**Comment by chiariniolivia** [comment]
this ended up being because of a difference in what variables meant within our scripts. we now have two different scripts that give the same number. moving forward, all code will be put into this repo.
